### ISSUE TITLE
API请求失败

### ISSUE THREAD

**Issue by leecheng310** [sazs34/MyActions#106]
API请求失败是什么原因··之前正常，修改了几个jdcookies就开始出错了，用lxk0301/scripts的版本可以

删除重新FORK也是一样症状~

**Comment by sazs34** [comment]
啥意思,具体哪个脚本报错内容发一下

**Comment by leecheng310** [comment]
开始【京东账号1】leecheng310

第1个京东账号的助力码:::0a74407df5df4fa99672a037eec61f7e@dbb21614667246fabcfd9685b6f448f3@6fbd26cc27ac44d6a7fed34092453f77@61ff5c624949454aa88561f2cd721bf6
格式化后第1个京东账号的助力码["0a74407df5df4fa99672a037eec61f7e","dbb21614667246fabcfd9685b6f448f3","6fbd26cc27ac44d6a7fed34092453f77","61ff5c624949454aa88561f2cd721bf6"]

东东农场: API查询请求失败 ‼️‼️
{"name":"RequestError","code":"ERR_INVALID_CHAR"}

❗️东东农场, 错误!
RequestError: Invalid character in header content ["cookie"]
    at Request._makeRequest (/home/runner/work/MyActions/MyActions/node_modules/got/dist/source/core/index.js:1174:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at ClientRequest.setHeader (_http_outgoing.js:473:3)
    at new ClientRequest (_http_client.js:203:14)
    at request (https.js:289:10)
    at Request._makeRequest (/home/runner/work/MyActions/MyActions/node_modules/got/dist/source/core/index.js:1121:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

❌ 东东农场, 失败! 原因: TypeError: Cannot read property 'farmUserPro' of undefined!


🔔东东农场, 结束! 🕛 0.153 秒

**Comment by sazs34** [comment]
Invalid character in header content ["cookie"]

有非法字符串在cookie里

**Comment by leecheng310** [comment]
京东的每个脚本都报错
下午还在用都正常，晚上删了几个京东的COOKIE就这样了，同样一套COOKIE放lxk0301/scripts可以正常

**Comment by leecheng310** [comment]
我再试试看··那估计是；的中英文吧
但是我都是从存档里复制的··放lxk0301/scripts又没事··奇怪··

**Comment by leecheng310** [comment]
星推官是又添加回来了么

**Comment by sazs34** [comment]
> 我再试试看··那估计是；的中英文吧
> 但是我都是从存档里复制的··放lxk0301/scripts又没事··奇怪··

讲道理,lxk0301那边可以的话,我这边不会失败的
多个cookie可以直接换行符分隔了

**Comment by sazs34** [comment]
> 星推官是又添加回来了么

加回来了,但是没有设置定时执行,纯hook调用

**Comment by leecheng310** [comment]
所以我也很奇怪···

**Comment by leecheng311** [comment]
找到原因了
cookie的锅
你这多京东cookie，要用&分隔就不报错
lxk0301原仓库是可以换行做分隔正常

**Comment by leecheng311** [comment]
也是今天lxk0301那出状况，又回来你这试出来的

**Comment by sazs34** [comment]
> 找到原因了
> cookie的锅
> 你这多京东cookie，要用&分隔就不报错
> lxk0301原仓库是可以换行做分隔正常

感谢，目前已支持lxk0301对cookie的解析
