### ISSUE TITLE
农场运行出错

### ISSUE THREAD

**Issue by Naughty-Monkey** [sazs34/MyActions#13]
```当前执行时间:Fri Sep 04 2020 22:57:12 GMT+0000 (Coordinated Universal Time)
当前共1个账号需要签到
下载代码完毕
替换变量完毕
/home/runner/work/MyActions/MyActions/onlyOneExecute.js:1097
    notify = $.isNode() ?  : '';
                           ^

SyntaxError: Unexpected token :
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
执行异常:Error: Command failed: node onlyOneExecute.js
执行完毕
```

**Comment by sazs34** [comment]
感谢分享,已修复

请参考下面链接同步最新的代码

http://www.ibloger.net/article/3361.html
