### ISSUE TITLE
京东每日签到报错

### ISSUE THREAD

**Issue by qhq** [sazs34/MyActions#153]
抱歉，好像我的问题特别多 ：）
刚加了tg推送，想试下，运行京东签到结果看log出错

**Comment by sazs34** [comment]
没看到你用我这边的代码呀，把报错链接发一下呢

**Comment by qhq** [comment]
https://github.com/qhq/OneForAll/runs/1411703981?check_suite_focus=true

`文件下载完毕
28
*****************开始京东账号1 qhqcz京豆签到*******************
29

30
⚠️⚠️⚠️⚠️目前Bark APP推送通知消息失败的,请换用其他通知方式,Bark对推送内容长度有限制 ⚠️⚠️⚠️⚠️
31

32
开始替换变量
33
替换变量完毕
34

35
开始执行脚本签到，请稍等
36
internal/modules/cjs/loader.js:834
37
京东签到脚本执行异常:Error: Command failed: /opt/hostedtoolcache/node/12.19.0/x64/bin/node /tmp/JD_DailyBonus.js >> /tmp/result.txt
38
  throw err;
39
internal/modules/cjs/loader.js:834
40
  ^
41
  throw err;
42

43
  ^
44
Error: Cannot find module 'request'
45

46
Require stack:
47
Error: Cannot find module 'request'
48
- /tmp/JD_DailyBonus.js
49
Require stack:
50
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
51
- /tmp/JD_DailyBonus.js
52
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
53
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
54
    at Module.require (internal/modules/cjs/loader.js:903:19)
55
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
56
    at require (internal/modules/cjs/helpers.js:74:18)
57
    at Module.require (internal/modules/cjs/loader.js:903:19)
58
    at require (internal/modules/cjs/helpers.js:74:18)
59
    at /tmp/JD_DailyBonus.js:2419:23
60
    at /tmp/JD_DailyBonus.js:2419:23
61
    at nobyda (/tmp/JD_DailyBonus.js:2428:5)
62
    at Object.<anonymous> (/tmp/JD_DailyBonus.js:103:15)
63
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
64
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
65
    at Module.load (internal/modules/cjs/loader.js:879:32) {
66
  code: 'MODULE_NOT_FOUND',
67
  requireStack: [ '/tmp/JD_DailyBonus.js' ]
68
}
69
    at nobyda (/tmp/JD_DailyBonus.js:2428:5)
70
    at Object.<anonymous> (/tmp/JD_DailyBonus.js:103:15)
71
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
72
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
73
    at Module.load (internal/modules/cjs/loader.js:879:32) {
74
  code: 'MODULE_NOT_FOUND',
75
  requireStack: [ '/tmp/JD_DailyBonus.js' ]
76
} `

**Comment by sazs34** [comment]
不要用bark了，长度限制
