### ISSUE TITLE
京喜每日签到报错

### ISSUE THREAD

**Issue by HenryTSZ** [sazs34/MyActions#185]
错误日志:

```
❗️京喜, 错误!
ReferenceError: doubleres is not defined
    at /home/runner/work/MyActions/MyActions/executeOnce.js:200:24
    at new Promise (<anonymous>)
    at showmsg (/home/runner/work/MyActions/MyActions/executeOnce.js:197:10)
    at /home/runner/work/MyActions/MyActions/executeOnce.js:43:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

🔔京喜, 结束! 🕛 19.609 秒
```

**Comment by Choicc** [comment]
好像是偶尔有这个,我第二遍就可以了,现在这个脚本加上多合一的一天总共会执行4次。应该问题不大。
