### ISSUE TITLE
新的互助码自动提交报错

### ISSUE THREAD

**Issue by pansj-dev** [sazs34/MyActions#246]
SYNCURL: https://raw.githubusercontent.com/sazs34/MyActions/master/backup/jd_shareCode_auto.js
2021-01-11T03:22:27.8600658Z ##[endgroup]
2021-01-11T03:22:27.9385692Z internal/modules/cjs/loader.js:638
2021-01-11T03:22:27.9389437Z     throw err;
2021-01-11T03:22:27.9390401Z     ^
2021-01-11T03:22:27.9390981Z 
2021-01-11T03:22:27.9392939Z Error: Cannot find module '/home/runner/work/MyActions/MyActions/execute.js'
2021-01-11T03:22:27.9394212Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2021-01-11T03:22:27.9395226Z     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2021-01-11T03:22:27.9396194Z     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2021-01-11T03:22:27.9397063Z     at startup (internal/bootstrap/node.js:283:19)
2021-01-11T03:22:27.9398131Z     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
2021-01-11T03:22:27.9414827Z ##[error]Process completed with exit code 1.

**Comment by sazs34** [comment]
已修复
