### ISSUE TITLE
jd_shareCode_auto.js-京东赚赚的自动提交助力码未成功，其他的都成功了

### ISSUE THREAD

**Issue by an0na** [sazs34/MyActions#254]
@sazs34 错误如下：

❗️京东分享码, 错误!
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at $.get (/home/runner/work/MyActions/MyActions/executeOnce.js:473:34)
    at isSurge.isLoon.isQuanX.isNode.got.on.then.t (/home/runner/work/MyActions/MyActions/executeOnce.js:540:4877)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by sazs34** [comment]
已修复
