### ISSUE TITLE
上游的控制农场和萌宠推送开关被砍，希望大佬不要跟着删掉呀。

### ISSUE THREAD

**Issue by MisterGlasses** [sazs34/MyActions#75]
优化sendNotify.js,移除控制农场和萌宠推送开关参数,腾讯云函数等云端用户如需控制农场和萌宠的推送,请直接修改脚本内的jdNotify即可
https://github.com/lxk0301/scripts/commit/e9ed39e940b3711ae1ace0bb970de265e599699b

**Comment by sazs34** [comment]
这个不影响git actions的处理的

**Comment by MisterGlasses** [comment]
> 这个不影响git actions的处理的

大佬能请教你一个问题吗？
我想整个GitHub上的电信签到 运行脚本时为什么提示如下
Error:Cannot find module crypto-js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (internal/modules/cjs/helpers.js:25:18)
at /home/runner/work/My-Actions/My-Actions/10000.js:15:29
at Object.<anonymous> (/home/runner/work/My-Actions/My-Actions/10000.js:19:3)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

原脚本用到了
  $.CryptoJS = $.isNode() ? require('crypto-js') : CryptoJS
  await signapp()
  await gethomeinfo()
  await showmsg()

**Comment by sazs34** [comment]
你项目根目录下有个package.json
其中
"dependencies": {
    "download": "^8.0.0",
    "request": "^2.88.2",
    "request-promise": "^4.2.5",
    "axios": "^0.19.2",
    "got": "^11.7.0",
    "tough-cookie": "^4.0.0"
  }
部分，里面加一行
"crypto-js": "^4.0.0",
就可以了

**Comment by MisterGlasses** [comment]
> "crypto-js": "^4.0.0",

大佬牛逼 不报错了 但还是没法签到😂
找不到 Key 对应的 DeviceToken, 请确保 Key 正确! Key 可在 App 端注册获得。
请在 BoxJs 填写手机号码!
我明明用secret替换了手机号

**Comment by MisterGlasses** [comment]
> 你项目根目录下有个package.json
> 其中
> "dependencies": {
> "download": "^8.0.0",
> "request": "^2.88.2",
> "request-promise": "^4.2.5",
> "axios": "^0.19.2",
> "got": "^11.7.0",
> "tough-cookie": "^4.0.0"
> }
> 部分，里面加一行
> "crypto-js": "^4.0.0",
> 就可以了

大佬我申请把你加成collaborator了 抽空帮我看看吧
