### ISSUE TITLE
喜马拉雅出错

### ISSUE THREAD

**Issue by lion-goose** [sazs34/MyActions#86]
只有一个账号，只填了time这个secret
文件同步完毕, 处理中...
14
Traceback (most recent call last):
15
  File "xmly_speed.py", line 45, in <module>
16
    run()
17
  File "xmly_speed.py", line 18, in run
18
    if not os.environ["XMLY_ACCUMULATE_INDEX"].strip()=='':
19
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/os.py", line 681, in __getitem__
20
    raise KeyError(key) from None
21
KeyError: 'XMLY_ACCUMULATE_INDEX'
22
Error: Process completed with exit code 1.

**Comment by sazs34** [comment]
处理中，稍后

**Comment by sazs34** [comment]
已修正
